"""Add nutritionist_id to models

Revision ID: 658974181e84
Revises: a27e156e7bf0
Create Date: 2026-02-22 18:03:39.255612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658974181e84'
down_revision = 'a27e156e7bf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nutritionist_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['nutritionist_id'], ['id'])

    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nutritionist_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['nutritionist_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nutritionist_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['nutritionist_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('nutritionist_id')

    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('nutritionist_id')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('nutritionist_id')

    # ### end Alembic commands ###
